apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::225336992303:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::225336992303:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16TCTT7B8OFOQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-13T18:49:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1200"
  uid: 3b8a44d2-04fe-4cc7-b049-9af255dc31f8
