apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::225336992303:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::225336992303:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n  groups:\n    - system:masters\n- rolearn: \u003cARN of instance role (not instance profile)\u003e\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-11-14T21:07:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6599"
  uid: 6ba89d60-5cf1-464c-ac9b-b66134597310
