apiVersion: v1
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::225336992303:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: \u003cARN of instance role (not instance profile)\u003e\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n- rolearn: arn:aws:iam::225336992303:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-11-13T18:49:52Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"136175","uid":"3b8a44d2-04fe-4cc7-b049-9af255dc31f8"}}
  creationTimestamp: "2021-11-13T18:49:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "137623"
  uid: 3b8a44d2-04fe-4cc7-b049-9af255dc31f8
